### ISSUE TITLE
where could find the Supplementary?

### ISSUE THREAD

**Issue by schwxd** [cuishuhao/BNM#2]
Thank you very much for the excellent work and sharing the code generously！

In Section 3.1 you mentioned the maximum of F-norm and the minimum of entropy could be achieved at the same value in Supplementary. I was wondering where could I find the Supplementary? I couldn't find it on the arxiv page.

Sorry for the bothering and thanks again.

**Comment by cuishuhao** [comment]
I upload the Supplementary to google driver and baidu cloud and the links could be found in Readme.

**Comment by schwxd** [comment]
Thank you very much for your kindness reply!
