### ISSUE TITLE
请教关于VisDA-2021中的相关方法

### ISSUE THREAD

**Issue by donggoing** [cuishuhao/BNM#23]
您好，我注意到您好像参与了VisDA-2021 Challenge
https://competitions.codalab.org/competitions/33396#results
如果不是您的话叨扰了！
如果是您的话我想请教一下您是否是使用了BNM的技术使得AUROC取得这么好的效果，想了解一下具体的做法。

**Comment by cuishuhao** [comment]
哈喽，
是使用了BNM，具体用法参考UODR任务下的使用方式，
https://github.com/cuishuhao/BNM/blob/master/UODR/train_loader.py#L197
即在全部类别上使用BNM

以及AUROC指标当时我们在一些CNN网络上效果更好些，具体有些忘了

**Comment by donggoing** [comment]
谢谢您的回复，我进行了一下尝试，奇怪的是我使用了之后ACC有所上升，但是AUROC却下降了，我感觉可能是我的计算过程存在问题，因为根据官方提供的dev-kit是需要给出未知类的置信度的，我想请问一下这边根据UODR的设置的话好像不能直接使用官方的[eval](https://github.com/VisionLearningGroup/visda21-dev/blob/e906d4642e3f486c97837e959885624dd398d668/eval.py#L38)方法，所以我做了一点调整，我想请问这边未知类的置信度是如何计算的，我是将所有closed class+1个unknown类做softmax然后取未知类的分数作为置信度，我感觉可能是这里有点问题。

**Comment by cuishuhao** [comment]
我记得好想有预估unknown个数，大体是closed class/5个（具体记不清），在这些类上做softmax

**Comment by donggoing** [comment]
好的，谢谢！我再尝试一下（如果能找到历史代码的话希望可以share一下，复现起来更方便一点，如果找不到的话也十分感谢！）

**Comment by donggoing** [comment]
你好，我还有点疑惑，论文里面关于DA的setting说的是还会apply bnm在labeled domain上，但是 [https://github.com/cuishuhao/BNM/blob/master/UODR/train_loader.py#L197](https://github.com/cuishuhao/BNM/blob/master/UODR/train_loader.py#L197) 好像只对target域计算了bnm？
