### ISSUE TITLE
核范数的计算

### ISSUE THREAD

**Issue by ctxqlxs** [cuishuhao/BNM#4]
在代码中， 你的计算方式 transfer_loss = -torch.mean(s_tgt)，使用的是均值而不是和，这里到底应该是和？还是均值呢？

**Comment by cuishuhao** [comment]
其实我感觉均值和sum本质上是相同的，论文中使用的|A|_*/B等于torch.mean(s_tgt)，从数学上奇异值的和（核范数）是一个比较有意义的变量，但实际使用中为了平衡不同loss的量级，均值是一个比较好的选择
