### ISSUE TITLE
use nuclear-norm instead of F-norm

### ISSUE THREAD

**Issue by weigq** [cuishuhao/BNM#5]
Hi, @cuishuhao , thanks for the code release.
I have some confusion about the details of the paper.
According to the inequality (5) in original paper, the two norms can bound each other. Thus, optimizing F-norm is equal to optimizing nuclear-norm. Why use the nuclear-norm instead of F-norm? The optimization of F-norm seems easier than nuclear-norm.
Thanks

**Comment by cuishuhao** [comment]
Two aspects to explain
1. 'bound each other' does not equal to 'the bigger, the bigger', such as 1<2<4<8(1,4 as a group,28 as the other group) then it might become 1.2<1.8<4.8<7.2. One group becomes bigger, another becomes smaller.
2. As in the paper, F-norm only denotes the discriminability, while nuclear norm denotes both the discriminability and diversity.

**Comment by weigq** [comment]
thanks for your quick reply.
